CREATE TABLE authorities
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE authorities_users
(
    authority_id BIGINT NOT NULL,
    users_id     BIGINT NOT NULL,
    CONSTRAINT pk_authorities_users PRIMARY KEY (authority_id, users_id)
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255)                            NOT NULL,
    first_name              VARCHAR(255)                            NOT NULL,
    last_name               VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    account_non_expired     BOOLEAN                                 NOT NULL,
    account_non_locked      BOOLEAN                                 NOT NULL,
    credentials_non_expired BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_authorities
(
    user_id        BIGINT NOT NULL,
    authorities_id BIGINT NOT NULL,
    CONSTRAINT pk_users_authorities PRIMARY KEY (user_id, authorities_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE authorities_users
    ADD CONSTRAINT fk_autuse_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id);

ALTER TABLE authorities_users
    ADD CONSTRAINT fk_autuse_on_user FOREIGN KEY (users_id) REFERENCES users (id);

ALTER TABLE users_authorities
    ADD CONSTRAINT fk_useaut_on_authority FOREIGN KEY (authorities_id) REFERENCES authorities (id);

ALTER TABLE users_authorities
    ADD CONSTRAINT fk_useaut_on_user FOREIGN KEY (user_id) REFERENCES users (id);