CREATE TABLE farm_users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    farm_id    BIGINT                                  NOT NULL,
    user_role  INTEGER                                 NOT NULL,
    created_at date                                    NOT NULL,
    CONSTRAINT pk_farm_users PRIMARY KEY (id)
);

CREATE TABLE farms
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    created_at  date                                    NOT NULL,
    CONSTRAINT pk_farms PRIMARY KEY (id)
);

ALTER TABLE farms
    ADD CONSTRAINT uc_farms_name UNIQUE (name);

ALTER TABLE farm_users
    ADD CONSTRAINT FK_FARM_USERS_ON_FARM FOREIGN KEY (farm_id) REFERENCES farms (id);

ALTER TABLE farm_users
    ADD CONSTRAINT FK_FARM_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

/* inserting defaults */
INSERT INTO farms (name, description, created_at)
    VALUES ('User farm', 'Farm created by the user', now());
INSERT INTO farm_users(user_id, farm_id, user_role, created_at) VALUES (
    (SELECT id FROM users WHERE username='user'),
    (SELECT id FROM farms WHERE name='User farm'),
    2,
    now());

INSERT INTO farms (name, description, created_at)
    VALUES ('Admin farm', 'Farm created by the admin', now());
INSERT INTO farm_users(user_id, farm_id, user_role, created_at) VALUES (
    (SELECT id FROM users WHERE username='admin'),
    (SELECT id FROM farms WHERE name='Admin farm'),
    2,
    now());

INSERT INTO farms (name, description, created_at)
    VALUES ('User shared farm', 'Farm created by the user, shared with admin', now());
INSERT INTO farm_users(user_id, farm_id, user_role, created_at) VALUES (
    (SELECT id FROM users WHERE username='user'),
    (SELECT id FROM farms WHERE name='User shared farm'),
    2,
    now());
INSERT INTO farm_users(user_id, farm_id, user_role, created_at) VALUES (
    (SELECT id FROM users WHERE username='admin'),
    (SELECT id FROM farms WHERE name='User shared farm'),
    0,
    now());

INSERT INTO farms (name, description, created_at)
VALUES ('Admin shared farm', 'Farm created by the admin, shared with user', now());
INSERT INTO farm_users(user_id, farm_id, user_role, created_at) VALUES (
                                                                           (SELECT id FROM users WHERE username='admin'),
                                                                           (SELECT id FROM farms WHERE name='Admin shared farm'),
                                                                           2,
                                                                           now());
INSERT INTO farm_users(user_id, farm_id, user_role, created_at) VALUES (
                                                                           (SELECT id FROM users WHERE username='user'),
                                                                           (SELECT id FROM farms WHERE name='Admin shared farm'),
                                                                           0,
                                                                           now());
