CREATE TABLE task_user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completed    BOOLEAN                                 NOT NULL,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT                                  NOT NULL,
    task_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_task_user PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT                                    NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    deadline    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    important   BOOLEAN                                 NOT NULL,
    creator_id  BIGINT,
    farm_id     BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_CREATOR FOREIGN KEY (creator_id) REFERENCES users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_FARM FOREIGN KEY (farm_id) REFERENCES farms (id);

ALTER TABLE task_user
    ADD CONSTRAINT FK_TASK_USER_ON_TASK FOREIGN KEY (task_id) REFERENCES tasks (id);

ALTER TABLE task_user
    ADD CONSTRAINT FK_TASK_USER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

INSERT INTO tasks(name, description, created_at, deadline, important, creator_id, farm_id)
    VALUES ('Task 1', 'Description 1', now(), now(), TRUE, 2, 4);
INSERT INTO task_user(completed, completed_at, user_id, task_id)
    VALUES (FALSE, null, 1, 1);