CREATE TABLE sensor_data
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    soil_moisture    DOUBLE PRECISION                        NOT NULL,
    soil_temperature DOUBLE PRECISION                        NOT NULL,
    air_humidity     DOUBLE PRECISION                        NOT NULL,
    air_temperature  DOUBLE PRECISION                        NOT NULL,
    longitude        DOUBLE PRECISION                        NOT NULL,
    latitude         DOUBLE PRECISION                        NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sensor_id        UUID,
    CONSTRAINT pk_sensor_data PRIMARY KEY (id)
);

CREATE TABLE sensors
(
    id          UUID         NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT pk_sensors PRIMARY KEY (id)
);

ALTER TABLE sensor_data
    ADD CONSTRAINT FK_SENSOR_DATA_ON_SENSOR FOREIGN KEY (sensor_id) REFERENCES sensors (id);